from .base_schema import BaseSchema
from .condition import ConditionSchema
from .healthcare_professional import HealthcareProfessionalSchema
from .medicine import MedicineSchema
from .occurrence import OccurrenceSchema
from .patient import PatientSchema
from .patient_condition import PatientConditionSchema
from .patient_medicine import PatientMedicineSchema
from .role import RoleSchema
from .user import UserSchema
