name: Code Quality

on:
  push:
    branches: ["main", "qa", "develop"]
  pull_request:
    branches: ["main", "qa", "develop"]
  workflow_dispatch:

jobs:
  check_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
      - name: Check code format (Black)
        run: black api --check --diff
      - name: Run static code analysis (Pylint)
        run: pylint api/doclog_api --disable=C0114,W0718,W0719,R0903,W0613
